### ISSUE TITLE
HL7 Dictionary Compile Issue - ORM_O01

### ISSUE THREAD

**Issue by helmut-steiner** [bexoft/finalmq#177]
When I make a complete build with CMake with HL7 v2.7.1 without the filter option of the demo the ORM^O01 message is visible in the final .h and .cpp files but I have to use the /bigobj compiler flag in Visual Studio. If I enable the filters via hl7options.json file and use the filter "ORM_O01" it doesn't include the ORM message. It cannot find it during the codegeneration process. 

I also tried compiling with CMake with HL7 v2.6 dictionary. There the codegeneration process works but the Visual Studio project does throw errors during compilation.

My current workaround is that I copied the ORM_O01 message format from the v2.6 dictionary into the v2.7.1 dictionary. This way it compiles and the filter finds the message. Any help is much appreciated!

![image](https://github.com/bexoft/finalmq/assets/8708898/e85cc1ac-7d02-4b2a-87a8-e8f27ccb784c)

**Comment by beckdave** [comment]
The message (Trigger Event) ORM_O01 is not part of v2.7.x anymore. Also without filter, the class of ORM_O01 is not generated. 

You can for example search for ORL_O36. This class is generated:

class SYMBOLEXP ORL_O36 : public finalmq::StructBase
{
public:
    hl7::MSH msh{};

But ORM_O01 is not part of 2.7.x anymore.

You can check the standard on this link:
[https://hl7-definition.caristix.com/v2/HL7v2.6/TriggerEvents/ORM_O01](https://hl7-definition.caristix.com/v2/HL7v2.6/TriggerEvents/ORM_O01)

When you change the version to 2.7 or 2.7.1 on this web-page, then you will get an error.

**Comment by helmut-steiner** [comment]
Yet it weirdly was available without filter. I already saw that it was deprecated since 2.4 (I think) and removed in 2.7 but it is one of the main message types that is used almost everywhere.

The main problem is that I tried to build the demo with 2.6 to have ORM available and it didn't compile without errors.

**Comment by beckdave** [comment]
The hl7 dictionary has some problems. I forked it and made some corrections for v2.7.1
You can look at my changes:
[https://github.com/beckdave/hl7-dictionary/commits/beckdave-fix-compounds](https://github.com/beckdave/hl7-dictionary/commits/beckdave-fix-compounds)

These similar changes are probably also needed for v2.6 to make it compilable.

**Comment by helmut-steiner** [comment]
Thanks!
One more unrelated question: Is there a way to get the raw incoming message prior to any processing through finalmq?

**Comment by beckdave** [comment]
In the RemoteEntityContainer::init there is one parameter, which you can set to true. In the receiving message structure, you can then also access the raw data.

**Comment by helmut-steiner** [comment]
Thanks a lot for your help and the quick responses!

**Comment by beckdave** [comment]
You are welcome

**Comment by beckdave** [comment]
I corrected v2.6 in hl7dictionary. It will now compile. But the hl7directory has to be cloned again, see:
CMakeLists.txt
CloneRepository("https://github.com/beckdave/hl7-dictionary.git" "beckdave-fix-compounds" "hl7-dictionary" "${FINALMQ_BINARY_DIR}/hl7-dictionary")

I guess, it should be enough to rerun cmake. If not, then rebuild all.
Tell me, if you have issues.

**Comment by helmut-steiner** [comment]
Thank you very much! 
I had another problem in a project which incorporates DCMTK and will open a separate issue.

**Comment by helmut-steiner** [comment]
After a few adaptations to the HL7 demo files everything works as expected! No more compilation errors on the dictionary. Thanks again!
I will make a pull request for a v2.6 real world ORM example once I get everything up and running in my project.
